Colunas 

1. acidez_fixa (g(ácido_tartárico)/dm³)

2. acidez_volátil (g(ácido_acético)/dm³)

3. ácido_cítrico (g/dm³)

4. açúcar_residual (g/dm³)

5. cloretos (g(cloreto_de_sódio)/dm³)

6. dióxido de enxofre livre (mg/dm³)

7. dióxido de enxofre total (mg/dm³)

8. densidade (g/cm³)

9. pH

10. sulfatos (g(sulfato_de_potássio)/dm³)

11. teor alcoólico (% vol.)

In [9]:
import pandas as pd

# Carregamento do arquivo CSV em um DataFrame do Pandas e substituição de ponto e vírgula por vírgula
vinho_tinto_dados = pd.read_csv('vinho_tinto.csv', sep=';', delimiter=None, engine='python')

# Dicionário de tradução dos nomes das colunas
traducao_colunas = {
    'fixed acidity': 'acidez_fixa',
    'volatile acidity': 'acidez_volatil',
    'citric acid': 'acido_citrico',
    'residual sugar': 'acucar_residual',
    'chlorides': 'cloreto',
    'free sulfur dioxide': 'dioxido_enxofre_livre',
    'total sulfur dioxide': 'dioxido_enxofre_total',
    'density': 'densidade',
    'pH': 'pH',
    'sulphates': 'sulfatos',
    'alcohol': 'alcool',
    'quality': 'qualidade'
}

# Renomeie as colunas com os nomes em português e padrão snake_case
vinho_tinto_dados.rename(columns=traducao_colunas, inplace=True)

# Modifique o índice para começar em 1
vinho_tinto_dados.index = vinho_tinto_dados.index + 1

# Salve o DataFrame em um novo arquivo CSV
vinho_tinto_dados.to_csv('vinho_tinto_traduzido.csv', sep=',', index_label='indice')

# Imprima o DataFrame no formato de tabela (no Jupyter Notebook, basta digitar o nome do DataFrame)
vinho_tinto_dados

,acidez_fixa,acidez_volatil,acido_citrico,acucar_residual,cloreto,dioxido_enxofre_livre,dioxido_enxofre_total,densidade,pH,sulfatos,alcool,qualidade
1,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
2,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
3,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
4,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
5,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1595,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1596,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1597,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1598,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1599,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6